swagger: "2.0"
info:
  title: flask
  version: 1.0.0
host: "localhost:3000"
schemes: 
  - http
basePath: "/api"
consumes: 
  - application/json
produces: 
  - application/json
paths:
  /users:
    get:
      tags:
        - user
      summary: 全ユーザー取得(sample)
      parameters:
        - in: query
          name: user_id
          type: integer
          format: int64